# Generated by Django 5.1.1 on 2024-10-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizendata',
            name='constituency',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='citizendata',
            name='photo_aadhaar',
            field=models.ImageField(upload_to='photos/photo1/'),
        ),
        migrations.AlterField(
            model_name='citizendata',
            name='photo_voter',
            field=models.ImageField(upload_to='photos/photo2/'),
        ),
    ]
