# Generated by Django 5.1.1 on 2024-10-07 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_name', models.CharField(max_length=100)),
                ('extracted_father_name', models.CharField(max_length=100)),
                ('extracted_dob', models.DateField()),
                ('extracted_address', models.TextField()),
                ('extracted_gender', models.CharField(max_length=10)),
                ('extracted_aadhaar_number', models.CharField(max_length=12)),
                ('extracted_voter_id', models.CharField(max_length=10)),
                ('extracted_photo', models.ImageField(upload_to='extracted_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_status', models.BooleanField(default=False)),
                ('voter_id_status', models.BooleanField(default=False)),
                ('photo_status', models.BooleanField(default=False)),
                ('verification_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
