# Generated by Django 5.1.1 on 2024-10-09 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadhaarVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_aadhaar_data_status', models.BooleanField(default=False)),
                ('upload_voter_card_data_status', models.BooleanField(default=False)),
                ('upload_photo_status', models.BooleanField(default=False)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.citizendata')),
            ],
        ),
    ]
