# Generated by Django 5.1.1 on 2024-10-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_id_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterid',
            name='constituency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
